### ISSUE TITLE
Some values appear to be abnormal when downloading over http

### ISSUE THREAD

**Issue by Suo-Ran** [yjl9903/naria2#361]
### Describe the bug

downloadSpeed and progress are not available for http downloads. They both have values of 0. Are they bugs or not currently supported?

The watchFollowedBy method was also not found

```javascript
const downloadUri =
  "https://cloudflare-ipfs.com/ipfs/QmYvVLJeW2FiTPtC19WWh7fnhZeMzMmK16QcBd6ervq7TD";

const client = await createClient(createChildProcess());

const p = await client.downloadUri(downloadUri, {
  dir: ".",
});

await p.watch((t) => {
  console.log(t.progress);
});

// not found function
// await p.watchFollowedBy((t) => {
//     console.log(t)
// })
```

### Used Package Manager

None

**Comment by yjl9903** [comment]
I think it should work, you can enable aria2 logs

```
const childprocess = await createChildProcess({
  log: './aria2.log'
});
const client = await createClient(childprocess);
```

**Comment by yjl9903** [comment]
Only torrent has watchFollowedBy due to the implementation of aria2

https://github.com/yjl9903/naria2?tab=readme-ov-file#usage

Due to the implementation of [aria2](https://aria2.github.io/manual/en/html/index.html), the downloading progress of a magnet uri includes two steps:

1. Download the torrent metadata which contains only a special file named [METADATA];
2. Download the torrent content itself.

So that, in the above code, you should first wait for downloading metadata, and then wait for downloading the followed by task which is the torrent content itself.

You can find an example using Node.js [here](https://github.com/yjl9903/naria2/blob/main/scripts/download.mjs).

**Comment by Suo-Ran** [comment]
Thank you very much. I found the problem. It seems that the download was too fast.

**Comment by yjl9903** [comment]
Ohh, I have make some changes: Before finishing downloading, call the watch function again. See https://github.com/yjl9903/naria2/commit/4a6bf4c3658402afdd601593641bb441d636d1ec

By the way, you can use `await torrent.updateStatus()` to refresh the latest progress.
